# Generated by Django 4.2.6 on 2023-10-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название продукта')),
                ('product_model', models.CharField(max_length=50, verbose_name='модель продукта')),
                ('launch_date', models.DateField(verbose_name='дата выхода продукта на рынок')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
